/* eslint-disable */
/**
 * Stub generated by repo-scaffolding. Run `npx convex dev` to replace with
 * deployment-linked typed API.
 */
import { anyApi } from 'convex/server';

export const api = anyApi;
export const internal = anyApi;
export const components = anyApi;
