/* eslint-disable */
/**
 * Stub generated by repo-scaffolding. Run `npx convex dev` to replace with
 * deployment-linked typed function builders.
 */
import {
	actionGeneric,
	httpActionGeneric,
	internalActionGeneric,
	internalMutationGeneric,
	internalQueryGeneric,
	mutationGeneric,
	queryGeneric
} from 'convex/server';

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const internalQuery = internalQueryGeneric;
export const internalMutation = internalMutationGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
